import React,{useEffect,useState} from 'react'
import api from '../services/api'
export default function Vehicles(){
  const [vehicles,setVehicles]=useState([]),[form,setForm]=useState({model:'',registrationNumber:'',capacity:4,status:'AVAILABLE'}),[editing,setEditing]=useState(null)
  useEffect(()=>{ api.get('/api/vehicles').then(r=>setVehicles(r.data)).catch(()=>{}) },[])
  function submit(){ if(editing){ api.put('/api/vehicles/'+editing.id,form).then(()=>api.get('/api/vehicles').then(r=>setVehicles(r.data))) } else { api.post('/api/vehicles',form).then(()=>api.get('/api/vehicles').then(r=>setVehicles(r.data))) } setForm({model:'',registrationNumber:'',capacity:4,status:'AVAILABLE'}); setEditing(null) }
  function edit(v){ setEditing(v); setForm({model:v.model,registrationNumber:v.registrationNumber,capacity:v.capacity,status:v.status}) }
  function remove(id){ if(confirm('Delete?')) api.delete('/api/vehicles/'+id).then(()=>api.get('/api/vehicles').then(r=>setVehicles(r.data))) }
  return (<div className='flex-1 p-8'><h1 className='text-2xl font-bold mb-4'>Vehicles</h1><div className='grid grid-cols-2 gap-4'><div className='p-4 bg-white rounded shadow'><h3 className='font-semibold mb-2'>{editing?'Edit Vehicle':'Add Vehicle'}</h3><input className='w-full p-2 border rounded mb-2' placeholder='Model' value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/><input className='w-full p-2 border rounded mb-2' placeholder='Registration' value={form.registrationNumber} onChange={e=>setForm({...form,registrationNumber:e.target.value})}/><input className='w-full p-2 border rounded mb-2' placeholder='Capacity' type='number' value={form.capacity} onChange={e=>setForm({...form,capacity:parseInt(e.target.value)})}/><select className='w-full p-2 border rounded mb-2' value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>AVAILABLE</option><option>IN_USE</option><option>MAINTENANCE</option><option>OFFLINE</option></select><button className='w-full p-2 bg-indigo-600 text-white rounded' onClick={submit}>{editing?'Save':'Create'}</button></div><div className='space-y-2'>{vehicles.map(v=>(<div key={v.id} className='p-3 bg-white rounded shadow flex justify-between'><div><div className='font-semibold'>{v.registrationNumber} · {v.model}</div><div className='text-sm text-slate-600'>Status: {v.status} | LastSeen: {v.lastSeen}</div></div><div className='flex flex-col gap-2'><button className='p-1 bg-yellow-400 rounded' onClick={()=>edit(v)}>Edit</button><button className='p-1 bg-red-400 rounded' onClick={()=>remove(v.id)}>Delete</button></div></div>))}</div></div></div>)
}
